### ISSUE TITLE
Auto deployment on GH pages

### ISSUE THREAD

**Issue by zekth** [reef-pi/website#49]
Would be easier to make the deployment to GH automaticly with Travis:

https://docs.travis-ci.com/user/deployment/pages/

**Comment by ranjib** [comment]
@zekth still interested? if so, you want to take a stab at this

**Comment by zekth** [comment]
i can, using Github actions yep

**Comment by ranjib** [comment]
i have setup github actions based auto deploy. we are also migrating the hugo  content to the reef-pi.github.io repo and getting rid of this repo
