### ISSUE TITLE
Deploy GitHub action doesn't work

### ISSUE THREAD

**Issue by hectorespert** [reef-pi/website#90]
Deploying reef-pi websiste using GitHub action doesn't work.

![Captura de pantalla_2020-11-22_13-59-01](https://user-images.githubusercontent.com/4323228/99904443-21ae8200-2ccb-11eb-8d79-ee040c2bad85.png)

**Comment by ranjib** [comment]
Im moving all the hugo plumbing to reef-pi.github.io and we will not need this repo anymore.
